version: '3'

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        image: api
        container_name: gg_api
        restart: unless-stopped
        env_file: api/.env
        ports:
            - "3000:3000"
        networks:
            - main
        command: node index.js
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        image: ui
        container_name: gg_ui
        restart: unless-stopped
        env_file: ui/.env
        ports:
            - "8080:8080"
        command: http-server dist
    db:
        image: mongo
        container_name: db
        restart: unless-stopped
        ports:
            - "27017:27017"
        networks:
            - main

networks:
    main:
        driver: bridge
