version: '3'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        image: node
        container_name: multiplayer_guessing_task
        restart: unless-stopped
        env_file: .env
        ports:
            - "3000:3000"
        networks:
            - main
        command: node index.js
    db:
        image: mongo
        container_name: db
        restart: unless-stopped
        ports:
            - "27017:27017"
        networks:
            - main

networks:
    main:
        driver: bridge
